/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectapotik;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class FormInputUser extends javax.swing.JFrame {
 
    ProjectApotik main = new ProjectApotik();
    Connection conn = main.ConnectDB();
    ResultSet rs = null;
    Statement stm;
    
    /**
     * Creates new form FormLogin
     */
    public FormInputUser() {
        initComponents();
    }
    
    private void ClearData(){
        jTxtIDUser.setText("");
        jTxtNamaUser.setText("");
        jTxtPassword.setText("");
        jTxtEncryptPass.setText("");
        jCmbJabatan.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtEncryptPass = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtIDUser = new javax.swing.JTextField();
        jTxtNamaUser = new javax.swing.JTextField();
        jTxtPassword = new javax.swing.JTextField();
        jCmbJabatan = new javax.swing.JComboBox<>();
        jOkSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Input User");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Jabatan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jTxtEncryptPass.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(jTxtEncryptPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 150, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("ID User");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Nama User");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jTxtIDUser.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(jTxtIDUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 130, 30));

        jTxtNamaUser.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(jTxtNamaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 310, 30));

        jTxtPassword.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTxtPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTxtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 150, 30));

        jCmbJabatan.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCmbJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- PILIH -", "Admin", "Kasir" }));
        getContentPane().add(jCmbJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 150, -1));

        jOkSimpan.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jOkSimpan.setText("Simpan");
        jOkSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOkSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(jOkSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 120, 40));

        setSize(new java.awt.Dimension(617, 544));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPasswordActionPerformed
        // TODO add your handling code here:
        String as = main.encryptPassMD5(jTxtPassword.getText());
        System.out.println(as);
    }//GEN-LAST:event_jTxtPasswordActionPerformed

    private void jOkSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOkSimpanActionPerformed
        // TODO add your handling code here:
        
        if (!jTxtIDUser.getText().isEmpty()) {
            if (!jTxtNamaUser.getText().isEmpty()) {
                if (!jTxtPassword.getText().isEmpty()) {
                    if (jCmbJabatan.getSelectedIndex() != 0) {
                        try {
                            String idUser, namaUser, passUser, jabatanUser;
                            idUser = jTxtIDUser.getText();
                            namaUser = jTxtNamaUser.getText();
                            passUser = main.encryptPassMD5(jTxtPassword.getText());
                            jabatanUser = jCmbJabatan.getSelectedItem().toString();

                            String sql = "INSERT INTO tblogin VALUES('" + idUser + "',"
                                                                  + "'" + namaUser + "',"
                                                                  + "'" + passUser + "',"
                                                                  + "'" + jabatanUser + "')";

                            stm = conn.createStatement();
                            stm.executeUpdate(sql);
                            stm.close();

                            JOptionPane.showMessageDialog(null, "Data user berhasil ditambahkan!");

                            ClearData();

                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, e.getMessage());
                        }
                    }else {
                        JOptionPane.showMessageDialog(null, "Anda belum memilih jabatan!");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Anda belum mengisi Password!");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Anda belum mengisi Nama User!");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Anda belum mengisi ID User!");
        }
        
    }//GEN-LAST:event_jOkSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInputUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInputUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInputUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInputUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormInputUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCmbJabatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jOkSimpan;
    private javax.swing.JTextField jTxtEncryptPass;
    private javax.swing.JTextField jTxtIDUser;
    private javax.swing.JTextField jTxtNamaUser;
    private javax.swing.JTextField jTxtPassword;
    // End of variables declaration//GEN-END:variables
}
