/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectapotik;

import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JTable;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class FormCariObat extends javax.swing.JFrame {
    
    Connection conn = null;
    ResultSet rs = null;
    Statement stm;

    private void ConnectDB(){
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost/dbapotik";
            String user = "root";
            String pass = "";
            
            conn = DriverManager.getConnection(url, user, pass);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi gagal" + e.getMessage());
            System.exit(0);
        }
    }
    
    private void displayData(){
        
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("Kode Obat");
        model.addColumn("Nama Obat");
        model.addColumn("Harga Beli");
        model.addColumn("Harga Jual");
        model.addColumn("Stok");
        
        try {
            String sql = "SELECT * FROM tbobat";
            stm = conn.createStatement();
            rs = stm.executeQuery(sql);
            
            while(rs.next()){
                model.addRow(new Object[]{
                    rs.getString("kodeobat"),
                    rs.getString("namaobat"),
                    rs.getString("hargabeli"),
                    rs.getString("harga1"),
                    rs.getString("stok")
                });
            }
            
            jTableObat.setModel(model);
            
            jTableObat.setRowHeight(30);
            
            jTableObat.setFont(new Font("", 0, 20));
            jTableObat.getTableHeader().setFont(new Font("", 1, 18));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }
    
    private void cariData(){
        
        DefaultTableModel model = new DefaultTableModel();
        
        String kategori = jCmbKategori.getSelectedItem().toString();
        String keyword = jTxtCari.getText();
        
        switch(kategori){
            case "Kode Obat":
                kategori = "kodeobat";
                break;
            case "Nama Obat":
                kategori = "namaobat";
                break;
            case "Kategori Obat":
                kategori = "namakategori";
                break;
            default:
                break;
        }
        
        try {
            String sql = "SELECT * FROM tbobat WHERE LOWER(" + kategori + ") LIKE LOWER('%" + keyword + "%')";
            stm = conn.createStatement();
            rs = stm.executeQuery(sql);
            
            // System.out.println(sql);
            
            model.addColumn("Kode Obat");
            model.addColumn("Nama Obat");
            model.addColumn("Harga Beli");
            model.addColumn("Harga Jual");
            model.addColumn("Stok");
            
            while(rs.next()){
                model.addRow(new Object[]{
                    rs.getString("kodeobat"),
                    rs.getString("namaobat"),
                    rs.getString("hargabeli"),
                    rs.getString("harga1"),
                    rs.getString("stok")
                });
            }
            
            jTableObat.setModel(model);
            
            stm.close();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Silahkan pilih kategori pencarian terlebih dahulu!");
        }
        
    }
    
    /**
     * Creates new form FormCariObat
     */
    public FormCariObat() {
        initComponents();
        ConnectDB();
        displayData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCmbKategori = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTxtCari = new javax.swing.JTextField();
        jOkCari = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableObat = new javax.swing.JTable();
        jOkExit = new javax.swing.JButton();
        jOkTambah = new javax.swing.JButton();
        jOkHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Cari Data Obat");
        setPreferredSize(new java.awt.Dimension(900, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Cari Data");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, 30));

        jCmbKategori.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- PILIH KATEGORI -", "Kode Obat", "Nama Obat", "Kategori Obat" }));
        getContentPane().add(jCmbKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Kategori");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, 30));

        jTxtCari.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTxtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtCariKeyPressed(evt);
            }
        });
        getContentPane().add(jTxtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 230, 35));

        jOkCari.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jOkCari.setText("Cari");
        jOkCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOkCariActionPerformed(evt);
            }
        });
        getContentPane().add(jOkCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 90, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detail Obat", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableObat);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 40, 730, 390));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 760, 450));

        jOkExit.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jOkExit.setText("Exit");
        jOkExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOkExitActionPerformed(evt);
            }
        });
        getContentPane().add(jOkExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 590, 130, -1));

        jOkTambah.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jOkTambah.setText("Tambah Data");
        jOkTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOkTambahActionPerformed(evt);
            }
        });
        getContentPane().add(jOkTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, -1, -1));

        jOkHapus.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jOkHapus.setText("Hapus Data");
        jOkHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOkHapusActionPerformed(evt);
            }
        });
        getContentPane().add(jOkHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 590, -1, -1));

        setSize(new java.awt.Dimension(877, 725));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jOkTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOkTambahActionPerformed
        // TODO add your handling code here:
        new FormObatApotik().setVisible(true);
        dispose();
    }//GEN-LAST:event_jOkTambahActionPerformed

    private void jOkHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOkHapusActionPerformed
        // TODO add your handling code here:
        int pesan = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (pesan == JOptionPane.YES_OPTION) {
            
            int row, col;
            String kodeobat;
            
            row = jTableObat.getSelectedRow();
            col = 0;
                    
            kodeobat = jTableObat.getModel().getValueAt(row, col).toString();
            
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
            
            try {
                String sql = "DELETE FROM tbobat WHERE kodeobat = '" + kodeobat + "'";
                stm = conn.createStatement();
                stm.executeUpdate(sql);
                displayData();
                stm.close();    
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
                
            }
            
        }
        
    }//GEN-LAST:event_jOkHapusActionPerformed

    private void jOkCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOkCariActionPerformed
        // TODO add your handling code here:
        cariData(); 
    }//GEN-LAST:event_jOkCariActionPerformed

    private void jOkExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOkExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jOkExitActionPerformed

    private void jTxtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCariKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cariData();
        }
    }//GEN-LAST:event_jTxtCariKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCariObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCariObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCariObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCariObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCariObat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCmbKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jOkCari;
    private javax.swing.JButton jOkExit;
    private javax.swing.JButton jOkHapus;
    private javax.swing.JButton jOkTambah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableObat;
    private javax.swing.JTextField jTxtCari;
    // End of variables declaration//GEN-END:variables
}
