/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectapotik;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class FormLoginUser extends javax.swing.JFrame {

    ProjectApotik main = new ProjectApotik();
    Connection conn = main.ConnectDB();
    ResultSet rs = null;
    Statement stm;
    
    /**
     * Creates new form FormLoginUser
     */
    public FormLoginUser() {
        initComponents();
    }
    
    private void Login(){        
        try {
            
            String user = jTxtIDUser.getText();
            String pass = main.encryptPassMD5(jTxtPassword.getText());
                
            if(user.isEmpty()){
                JOptionPane.showMessageDialog(null, "Gagal login! \nID belum terisi!");
                
            }else if(jTxtPassword.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Gagal login! \nPassword belum terisi!");
                
            }else{
                String sql = "SELECT * FROM tblogin WHERE iduser = '" + user + "' AND password = '" + pass + "'";
                stm = conn.createStatement();
                rs = stm.executeQuery(sql);

                String idUser, passUser, namaUser, jabatanUser;
                idUser = null;
                namaUser = null;
                passUser = null;
                jabatanUser = null;

                while(rs.next()){
                    idUser = rs.getString("iduser");
                    namaUser = rs.getString("namauser");
                    passUser = rs.getString("password");
                    jabatanUser = rs.getString("jabatan");
                
                }

                if (user.equals(idUser) && pass.equals(passUser)) {
                    JOptionPane.showMessageDialog(null, "Berhasil Login!");
                    FormUtama log = new FormUtama();

                    log.jTxtIDUser.setText(idUser);
                    log.jTxtNamaUser.setText(namaUser);
                    log.jTxtJabatanUser.setText(jabatanUser);
                    log.setVisible(true);
                    this.dispose();
                
                }else{
                    JOptionPane.showMessageDialog(null, "Gagal login! \nSilahkan periksa kembali ID atau Password Anda!");
                
                }
                
                System.out.println(sql);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTxtPassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtIDUser = new javax.swing.JTextField();
        jOkLogin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login User");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("ID User");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jTxtPassword.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTxtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 160, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jTxtIDUser.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(jTxtIDUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 160, 30));

        jOkLogin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jOkLogin.setText("Login");
        jOkLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOkLoginActionPerformed(evt);
            }
        });
        jOkLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jOkLoginKeyPressed(evt);
            }
        });
        getContentPane().add(jOkLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 120, 40));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("FORM LOGIN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 70));

        setSize(new java.awt.Dimension(504, 455));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jOkLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOkLoginActionPerformed
        // TODO add your handling code here:
        Login();
    }//GEN-LAST:event_jOkLoginActionPerformed

    private void jTxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPasswordActionPerformed
        // TODO add your handling code here:
        Login();
    }//GEN-LAST:event_jTxtPasswordActionPerformed

    private void jOkLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jOkLoginKeyPressed
        // TODO add your handling code here:
        Login();
    }//GEN-LAST:event_jOkLoginKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLoginUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLoginUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jOkLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtIDUser;
    private javax.swing.JTextField jTxtPassword;
    // End of variables declaration//GEN-END:variables
}
